name: result_type
version: 0.1.0
description: Result Type represents either a success or a failure, including an associated value in each case.
repository: https://github.com/epam-cross-platform-lab/dart_result_type

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  http: ^0.13.0
  test: ^1.16.8