name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed lib test example

      - name: Analyze project source
        run: dartanalyzer --fatal-infos --fatal-warnings lib test example
        
      - name: Run example
        run: dart run example/example.dart

      - name: Active coverage
        run: pub global activate coverage

      - name: Run tests
        run: dart test test/test_all.dart

      - name: Start Observatory
        run: dart
         --disable-service-auth-codes
         --enable-vm-service=8111
         --pause-isolates-on-exit
         --enable-asserts
         test/test_all.dart &

      - name: Collect coverage
        run: nohup pub global run coverage:collect_coverage
          --port=8111
          --out=coverage.json
          --wait-paused
          --resume-isolates

      - name: Format coverage
        run: pub global run coverage:format_coverage
          --lcov
          --in=coverage.json
          --out=lcov.info
          --packages=.packages
          --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: lcov.info
          min_coverage: 100

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
